### PR TITLE
Enable install not only paid apps

### PR DESCRIPTION
**Pull request by Luavis**
Fix issue #19

### CODE REVIEW

**Comment by argon** [comment]
Could you provide some more details about this change?

**Comment by Luavis** [comment]
The origin mas can't download ```Slack``` and ```Weather Live Free``` which are free apps from appstore. when I tested with new parameter that this commit change, it works.

**Comment by argon** [comment]
Have you also tested with paid apps to ensure they redownload correctly?

**Comment by Luavis** [comment]
Yes. I tested with ```Apple Remote Desktop``` and it definitely work.

**Comment by Luavis** [comment]
Do you need more testing samples?

**Comment by argon** [comment]
@Luavis this fix didn't work for me but I did find an alternative solution which is now in `master`

**Pull request closed without merging**
