### PR TITLE
WIP: Support `mas login`

### PR DESCRIPTION
**Pull request by cybertk**
Add support to login to MAS with `mas login --appleId <apple_id> --password <password>`

You can install this version of **mas** with

```shell
brew install cybertk/formulae/mas --HEAD --env=std
```

### CODE REVIEW

**Comment by cybertk** [comment]
Current TODOs:

- [ ] Prettify execution log
- [ ] Updated usage guide
- [ ] Give better instructions to enable Accessibility Permission

**Comment by argon** [comment]
Just saw this. I'm not comfortable including arbitrary AppleScript in the app at the moment. Have you checked whether this can be done in the SDK directly? If not is there a way to perform the accessibility commands directly from Cocoa instead of embedded AppleScript?

**Comment by cybertk** [comment]
I spent a long time to find how to login with API in **CommerceKit** and **StoreFoundation**, but no progress.

What do you mean **is there a way to perform the accessibility commands directly from Cocoa**

**Comment by cybertk** [comment]
I cannot find a CLI way to grant **mas** Accessibility Permission on El Capitan. I tried [jacobsalmela/tccutil](https://github.com/jacobsalmela/tccutil) with `tccutil -i /path/to/mas`, but it does not work.

I also observed that

- When running **mas** in **Terminal.app**, grant Accessibility Permission to **Terminal.app** is worked
- When running **mas** in **Xcode**(Debug),  grant Accessibility Permission to **Xcode.app** is worked

**Comment by argon** [comment]
I am referring to this API https://developer.apple.com/library/mac/documentation/ApplicationServices/Reference/AXUIElement_header_reference/ instead of using AppleScript.

**Comment by argon** [comment]
Did you update the headers to see the API that I trimmed from the `PrivateHeaders` in the repository? If you pull the latest `master` (I had to fix something) and call `script/update_headers` you will see a lot more header files.

I have identified some headers which are worth exploration:
```
mas-cli/PrivateHeaders/CommerceKit/CKAccountAuthentication.h
mas-cli/PrivateHeaders/StoreFoundation/ISAccountService-Protocol.h
mas-cli/PrivateHeaders/StoreFoundation/ISAuthenticationChallenge.h
mas-cli/PrivateHeaders/StoreFoundation/ISSignInPrompt.h
mas-cli/PrivateHeaders/StoreFoundation/ISStoreAuthenticationChallenge.h
```

There should be enough API's to perform a sign in without showing any UI as that is the full API that the App Store app uses.

**Comment by cybertk** [comment]
I agree with you @argon. After some experiments I found it's not some direct APIs calls to implement login, it more like some of these APIs are depended on the others. If we can know how Apple's MAS using those APIs, there would be easier to understanding the login flow.

**Comment by argon** [comment]
I have added this command here d80ad6e866378504c11aeb2e47692977954bd05d.

It is included in v1.1.0 which is available from Homebrew

**Comment by cybertk** [comment]
You are aaaaaawesome. How can you find find the login flow? I'm very curious about that.

**Comment by argon** [comment]
I spent a couple of hours exploring `StoreFoundation.framework` (and friends) with a debugger and experimenting with the different code paths I found. It took a lot of trial and error before I noticed that the demo mode override was triggered before any other UI and it worked perfectly

**Pull request closed without merging**
